### ISSUE TITLE
Running into errors while following the Readme;

### ISSUE THREAD

**Issue by tanayvarshney** [brollb/simple-0ad-example#4]
Hi @brollb,

I was trying to use your repo and ran into the following:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
== Status ==
Current time: 2022-01-11 19:30:47 (running for 00:00:00.11)
Memory usage on this node: 4.1/15.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/1 GPUs, 0.0/7.61 GiB heap, 0.0/3.81 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/tanay/ray_results/default
Number of trials: 1/1 (1 PENDING)
+-----------------------------------+----------+-------+
| Trial name                        | status   | loc   |
|-----------------------------------+----------+-------|
| PPO_CavalryVsInfantry_08635_00000 | PENDING  |       |
+-----------------------------------+----------+-------+

......
......

(RolloutWorker pid=7656)   File "/usr/local/lib/python3.6/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 459, in __init__
(RolloutWorker pid=7656)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=7656)   File "/home/tanay/zero_ad_rl/zero_ad_rl/env/__init__.py", line 5, in <lambda>
(RolloutWorker pid=7656)     register_env('CavalryVsInfantry', lambda c: CavalryVsInfantryEnv(c))
(RolloutWorker pid=7656)   File "/home/tanay/zero_ad_rl/zero_ad_rl/env/cav_vs_inf.py", line 63, in __init__
(RolloutWorker pid=7656)     super().__init__(config, AttackRetreat(), EnemyDistance())
(RolloutWorker pid=7656) TypeError: __init__() missing 1 required positional argument: 'state_builder'
(RolloutWorker pid=7693) 2022-01-11 19:30:49,028	WARNING deprecation.py:46 -- DeprecationWarning: `callbacks dict interface` has been deprecated. Use `a class extending rllib.agents.callbacks.DefaultCallbacks` instead. This will raise an error in the future!
(RolloutWorker pid=7693) 2022-01-11 19:30:49,028	ERROR worker.py:431 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=7693, ip=10.0.0.196)
(RolloutWorker pid=7693)   File "/usr/local/lib/python3.6/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 459, in __init__
(RolloutWorker pid=7693)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=7693)   File "/home/tanay/zero_ad_rl/zero_ad_rl/env/__init__.py", line 5, in <lambda>
(RolloutWorker pid=7693)     register_env('CavalryVsInfantry', lambda c: CavalryVsInfantryEnv(c))
(RolloutWorker pid=7693)   File "/home/tanay/zero_ad_rl/zero_ad_rl/env/cav_vs_inf.py", line 63, in __init__
(RolloutWorker pid=7693)     super().__init__(config, AttackRetreat(), EnemyDistance())
(RolloutWorker pid=7693) TypeError: __init__() missing 1 required positional argument: 'state_builder'

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I am on Ubuntu 18.04, using python 3.6.9 and followed the following steps:

- Installed 0ad
- Installed the client here: https://github.com/0ad/0ad/tree/master/source/tools/rlclient/python
- cloned this repo
- pip3 install -e .
- pyrogenesis 0ad_rl_maps.zip
- pyrogenesis --rl-interface=0.0.0.0:6000 --autostart-nonvisual --mod=rl-scenarios --mod=public
- python3 -m zero_ad_rl.train --env CavalryVsInfantry --run PPO --checkpoint-freq 100

Just to make sure that the base installations are installed correctly, I tried using the python client that comes with 0ad and it worked (https://github.com/0ad/0ad/blob/master/source/tools/rlclient/python/samples/simple-example.py)

I am not quite sure how to resolve this issue. Any comments would really help!

**Comment by brollb** [comment]
Hi @tanayvarshney! Thanks for reaching out. There was a minor issue introduced in the last refactor (focused on reusable state/action/reward builders) which introduced a bug. It should be resolved now!

Let me know if you have any other issues or questions! The documentation is pretty light right now so don't hesitate to just open an issue or shoot me an email :) A couple things that should be added to the docs:
- The default reward builder is currently just 0/1 reward (ie, there is no reward shaping) so it will take a little longer to learn as a result (as opposed to adding shaping like damage dealt vs received, etc).
- There are some tools for extracting trajectories from 0 AD replay files (required for imitation learning).
- As you probably noticed, the training/rollout code is just a thin layer over RLlib. This is great bc they have a large number of useful features like distributed training and various training algorithms that we get for (almost) free.
- That said, distributed training needs to be updated. Should be pretty simple if it is something you are interested in. Basically, RLlib provides a `worker_index` in their config which can be used to assign them to a game server. In the past (prior to the refactor), I just spun up a bunch of versions of the game on consecutive ports then used the worker_index to assign the workers to their own game instance.

**Comment by brollb** [comment]
Also, here are some other resources/walkthroughs:
- https://trac.wildfiregames.com/wiki/GettingStartedReinforcementLearning
- https://brollb.github.io/machine-learning/games/2021/02/28/0ad-rl-custom-spaces/

**Comment by tanayvarshney** [comment]
@brollb Thanks a tonne for the prompt fix and sharing your article. I will keep an eye out for the points you mentioned!
